plugins {
    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.148' apply false
    // https://maven.fabricmc.net/net/fabricmc/fabric-loom-remap/ (1.18 needs Java 25 to run Gradle)
    id 'net.fabricmc.fabric-loom-remap' version '1.17.21' apply false
}
