pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Official NeoForge Maven'
            url = 'https://maven.neoforged.net/releases'
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = 'https://maven.fabricmc.net/'
                }
            }
            filter {
                includeGroupAndSubgroups 'net.fabricmc'
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'capsule'
include('common')
include('neoforge')
include('fabric')
